/*
 * Copyright (C) Sportradar AG. See LICENSE for full license governing this code
 */
namespace Sportradar.MTS.SDK.Entities.Enums
{
    /// <summary>
    /// Enumerates products which use the feed
    /// </summary>
    internal enum Product
    {
        /// <summary>
        /// Indicates the message was generated by the live-odds product
        /// </summary>
        LiveOdds = 1,

        /// <summary>
        /// Indicates the message was generated by the MTS (Managed Trading Services) product
        /// </summary>
        Mts = 2,

        /// <summary>
        /// Indicates the message was generated by the LCoO (Live Cycle of Odds) product
        /// </summary>
        Lcoo = 3,

        /// <summary>
        /// Indicates the message was generated by the BetPal
        /// </summary>
        Betpal = 4,

        /// <summary>
        /// Indicates the message was generated by the PremiumCricket
        /// </summary>
        PremiumCricket = 5,

        /// <summary>
        /// Indicates the message was generated by the virtual sports product
        /// </summary>
        Virtuals = 6
    }
}